exclude: [ _posts/source ]
highlighter: pygments
safe: false
paginate: 6

tag_page_layout: tag_page
tag_page_dir: tag

markdown: Pandoc

author:
  name: Marco Rizzoli
  givenName: Marco
  familyName: Rizzoli
  github: mrizzoli
url: http://rizzoli.me.uk
title: Notes and stuff by Marco Rizzoli
name: Notes and stuff by Marco Rizzoli
